import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "inverse-primary": "#b9c3ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0d46f8",
        "primary-fixed-dim": "#b9c3ff",
        "surface": "#f7f9fb",
        "secondary-fixed": "#dfe2f1",
        "surface-container-low": "#f2f4f6",
        "secondary": "#5a5e6a",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#c3c6d4",
        "on-secondary-fixed": "#171b26",
        "tertiary-container": "#00744f",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#434652",
        "on-surface-variant": "#434656",
        "outline-variant": "#c4c5d9",
        "primary": "#0038d3",
        "on-primary-fixed": "#001258",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#0032c3",
        "on-primary-container": "#dfe2ff",
        "error-container": "#ffdad6",
        "outline": "#747688",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#00593c",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#70fcbf",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-container": "#dfe2f1",
        "on-secondary-container": "#606471",
        "on-error-container": "#93000a",
        "primary-fixed": "#dee1ff",
        "primary-container": "#1f4fff",
        "surface-container-high": "#e6e8ea",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        gutter: "1rem",
        margin: "1rem",
        "gutter-md": "1.5rem",
        "margin-md": "2rem",
        "gutter-lg": "2rem",
        "margin-lg": "3rem",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
      keyframes: {
        "slide-up": {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "slide-up": "slide-up 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
